- README.md
Match product naming from Google and add a link to the npm package page.
> docs: update names and links in README

- src/components/advanced-marker.tsx
- src/components/marker.tsx
In strict mode, the effect-hook that creates the marker is run twice in quick succession, so we can't rely on the state to refer to the marker.
fixes #14
> fix: markers not removed in strict mode

- examples/basic-map/src/control-panel.tsx
- fix basic map example code link to point to the correct sub folder
> docs: point basic map example code link to matching url

- docs/contributing.md
- website/docusaurus.config.js
As we don't have a `master` branch, adjust links to use the correct name (although Github redirects them correctly)
> docs: adjust branch naming in links, master -> main

- docs/interacting-with-the-google-maps-api.md
- docs/table-of-contents.json
- add first version of a docs page to show what the options are to interact with the google maps api (hooks, refs, useMapsLibrary/custom hook)
> docs: interact with google maps api

- docs/api-reference/components/api-provider.md
- docs/api-reference/components/info-window.md
- docs/api-reference/components/map.md
- docs/api-reference/components/marker.md
- use the correct package name in the examples
> docs: use correct package name in examples

- docs/api-reference/components/map-control.md
- docs/table-of-contents.json
- src/components/__tests__/map-control.test.tsx
- src/components/map-control.tsx
- src/index.ts
Adds a new component `MapControl` that allows users to add custom react components to the controls of a Map instance.
Example:
```tsx
import {APIProvider, Map, MapControl, ControlPosition} from '@vis.gl/react-google-maps';
const App = () => (
<APIProvider apiKey={'...'}>
<Map {...mapProps}>
<MapControl position={ControlPosition.TOP_LEFT}>
.. any component here will be added to
the control-containers of the google map instance ..
</MapControl>
</Map>
</APIProvider>
);
```
> feat: new MapControl component

- src/components/__tests__/map.test.tsx
- src/components/map/index.tsx
- src/components/map/use-internal-camera-state.ts
- src/components/map/use-map-events.ts
- src/components/map/use-map-options.ts
- src/libraries/is-lat-lng-literal.ts
Camera state tracking allows the Map component to avoid a feedback-loop when camera values published by the map are fed back into the Map component props.
I measured round-trip times (dispatching an event into the react-application and receiving them back as props) of around 4-5ms. However, there are cases where this roundtrip crosses the frame-boundary, and times more like 20ms can be observed. When this happens, stuttering, janky animations and suboptimal interactions will happen.
> fix: add map camera state tracking

- package-lock.json
- package.json
we are reusing types from the @types/google.maps package for things like MapProps etc. To make sure those types are available when installing this package, we have to specify them as dependencies instead of devDependencies.
fixes #106
> fix: move @types/google.maps to dependencies

- examples/examples.css
> docs: make control panel and info window text readable in dark mode

- docs/README.md
Hi, I found that the "introduction" page (https://visgl.github.io/react-google-maps/docs generated from `docs/README.md`) had two broken links.
These were caused by an extra newline between anchor text and alias links in Markdown, probably due to the autoformatting. This PR fixes it by adjusting newline positions while keeping up to 80 characters/line.
> docs: fix link label errors

- src/components/api-provider.tsx
`importLibrary()` depends on `loadedLibraries` but that is not stated in the deps array. This cause check: 
```js
if (loadedLibraries[name]) {
return loadedLibraries[name];
}
```
Not working, because `loadedLibraries` always empty and therefore every `importLibrary()` call even for libraries which are already loaded cause full re-render of all components depending on map context.
> fix: avoid re-render on every importLibrary() call

- src/components/advanced-marker.tsx
fix #142
If we want to use `classList.add` to add multiple class names while keeping the existing class names, we could write like this:
```ts
const classNames = className.split(' ')
el.classList.add(...classNames);
```
But we simply add class names to a brand new `div` element here so I think we can add the provided `className` as is.
> fix: allow AdvancedMarker to accept space-separated multiple class names

- docs/api-reference/components/map.md
Fix markdown link in first sentence in the MapProps docs https://visgl.github.io/react-google-maps/docs/api-reference/components/map#props
> Fix link in Map component docs

- src/components/__tests__/marker.test.tsx
- src/components/advanced-marker.tsx
- src/components/info-window.tsx
- src/components/map/use-map-events.ts
- src/components/marker.tsx
- src/libraries/google-maps-api-loader.ts
As discovered in #137, there are apparently situations where the `.addListener()` function that components inherit from the MVCObject class will return undefined in certain edge cases, like when the Map is rendering the fallback-screen for an invalid API-key.
Therefore we will use the hopefully more stable `google.maps.event.addListener` method everywhere.
> fix: don't use potentially unreliable addListener functions

- src/components/__tests__/api-provider.test.tsx
- src/components/__tests__/map.test.tsx
- src/components/api-provider.tsx
- src/components/map/index.tsx
- src/hooks/__tests__/api-loading.test.tsx
- src/hooks/__tests__/use-map.test.tsx
- src/hooks/use-api-is-loaded.ts
- src/hooks/use-api-loading-status.ts
- src/libraries/__mocks__/google-maps-api-loader.ts
- src/libraries/api-loading-status.ts
- src/libraries/google-maps-api-loader.ts
Introduces handling for API-key errors (via the gm_authFailed callback) for the map-component.
This also shifts responsibility for tracking the loading status into the GoogleMapsApiLoader class, to avoid problems when the APIProvider itself is rendered conditionally.
> feat: handle API-key errors in map-component

- src/components/advanced-marker.tsx
- src/components/info-window.tsx
- src/components/map-control.tsx
- src/components/marker.tsx
- src/components/pin.tsx
- src/hooks/use-maps-library.ts
This should fix the double rendering issues of the infowindow causing problems (#109 #175)
- Restructure infowindow to handle options update and callback update without having to re-render the whole infowindow which would cause flickering
- Handle className update in the AdvancedMarker component without having to re-render the marker which would cause flickering of the marker
- fix a few eslint warning by deliberately disabling the `react-hooks/exhaustive-deps` on a few lines
> fix(infowindow): fix double rendering and fix eslint warnings

- src/libraries/use-deep-compare-effect.tsx
In the compiled esm-package, the import of `fast-deep-equal/react` is producing errors (seems like it should have been transformed into `fast-deep-equal/react.js` at somoe point during build. But since I don't think we actually need the react-specific parts of fast-deep-equal, we can just leave that away for now and figure out how to do these deep imports correctly later.
fixes #207
> fix: remove deep-link into fast-deep-equal package

- src/components/map/use-map-instance.ts
Hi, this is a simple fix to address one ESLint warning.
ref. https://github.com/visgl/react-google-maps/actions/runs/7817624474/job/21325966198#step:5:25
> refactor(use-map-instance): remove unused import

- docs/api-reference/components/map.md
Just found two small link syntax errors 🙂 
This fixes the following two places:
- https://visgl.github.io/react-google-maps/docs/api-reference/components/map#props:~:text=The%20MapProps%20type%20extends%20the
- https://visgl.github.io/react-google-maps/docs/api-reference/components/map#props:~:text=The%20Google%20Maps%20API%20Documentation
> docs: fix a link error in `map.md`

- src/components/info-window.tsx
realized that if shouldFocus is set to false, then it will not be set at all in the open call, so added distinguisher from null, sorry for the oversight!
> fix a bug where false would not be detected as parameter false

- src/components/advanced-marker.tsx
- src/components/api-provider.tsx
- src/components/map/index.tsx
Add memoization to all context values used internally. Without the memoization, the context value of e.g. the GoogleMapsContext (used to retrieve the map-instance in the `useMap` hook) will register as changed every time the map-component re-renders, causing all children that use the context (for example via the `useMap` hook) to re-render as well. With the memoization in place, these unnecessary renders will no longer happen.
fixes #285
> fix: memoize context-values to avoid excessive re-renders

- src/components/advanced-marker.tsx
- src/components/marker.tsx
> feat: dissalow map prop for markers

- src/components/advanced-marker.tsx
- src/components/info-window.tsx
- src/components/marker.tsx
Just few swaps of `useContext` into convienient `useMap`.
swap in:
> refactor: use useMap in couple of places

- docs/api-reference/components/api-provider.md
- src/components/__tests__/api-provider.test.tsx
- src/components/api-provider.tsx
The Maps JavaScript API loader supports a parameter `solutionChannel` ([documentation](https://developers.google.com/maps/documentation/javascript/load-maps-js-api#optional_parameters)). This pull request adds support for the parameter, provides a default value if none is provided to override it, and adds a test to verify that it gets passed to the actual loading script.
> feat: add support for solution-channel parameter

- .eslintrc.js
- .vscode/settings.json
eslint should now report missing dependencies when using `useDeepCompareEffect`.
> chore(eslint): add useDeepCompareEffect to exhaustive deps rule

- docs/api-reference/components/map.md
- src/components/__tests__/map.test.tsx
- src/components/map/index.tsx
- src/components/map/use-map-instance.ts
Introduces map-instance caching, allowing maps to be persisted across unmount/remount cycles.
Fixes #319 
BREAKING CHANGE: Introduction of map instance caching needed a change to the DOM-Structure produced by the map component (added a div-element owned by the Map component to contain the map instance).
> feat(map): implement initial version of map-instance caching

- src/components/advanced-marker.tsx
In PR https://github.com/visgl/react-google-maps/pull/335, the `InfoWindow` cleanup function removes the content element. We should implement the same behavior for the `AdvancedMarker` component to ensure proper cleanup of its content element as well.
https://github.com/visgl/react-google-maps/blob/bc10a6f3a64e7445bc8b672375c9d196b7899d9e/src/components/info-window.tsx#L78-L83
> feat(advanced-marker): remove content element in cleanup

- src/components/map/use-map-instance.ts
Introduction of the intermediate div with #349 indirectly broke relative positioning of elements withing the map-container.
Before that change, elements would be added to a container where position:relative was set by the Maps JavaScript API. This is no longer happening, so we need to set it ourselves.
> fix(map): set container position to relative

- src/components/map/index.tsx
- src/components/map/use-map-instance.ts
The change in #356 did the right thing, but added the position:relative to the wrong element.
> fix(map): set other container position to relative

- examples/marker-clustering/src/app.tsx
Just added ControlPanel to marker-clustering example.
The component was there, but it was not loded from `<App />`.
> added ControlPanel to marker-clustering example

- docs/api-reference/components/advanced-marker.md
- src/components/__tests__/advanced-marker.test.tsx
- src/components/__tests__/info-window.test.tsx
- src/components/advanced-marker.tsx
Previously, the AdvancedMarker would only apply the className prop to the content when custom html contents were specified, but there are some cases (applying css-animations to markers for example) where we also want the className to apply to markers that just contain a PinElement.
This also contains a rewrite and extension of the AdvancedMarker tests.
Fixes #374
> fix(advanced-marker): apply marker class when rendering a Pin

- src/components/info-window.tsx
- src/hooks/use-maps-event-listener.ts
An InfoWindow that is attached to a Marker or AdvancedMarker as anchor would occasionally show up again after being unmounted. This can happen when the anchor is removed from the map before the InfoWindow is unmounted but gets re-added to the map at a later point.
This is caused by intended behavior in the maps API, and the only workaround for this right now is to forcefully disconnect the InfoWindow from its anchor.
See here for more details: https://issuetracker.google.com/issues/343750849
Fixes #386
Co-Authored-By: Nick Schnelle <nick.schnelle@bupa.com.au>
> fix(info-window): fix reappearing InfoWindows

- docs/api-reference/components/map.md
- src/components/__tests__/map.test.tsx
- src/components/map/index.tsx
- src/components/map/use-map-instance.ts
As discussed in issue #391, this PR adds the optional `padding` property to `defaultBounds`.
e.g.
```javascript
<Map
defaultBounds={{
west: -7.521054546833144,
north: 57.18946776545227,
south: 49.60181300450985,
east: -2.8939254862738877,
padding: {
bottom: 50,
right: 50,
}
}}
/>
```
NOTE
The Google Maps API implement a system of discreet zoom levels, so some values of padding could not be visible if they don't reach the smallest amount of padding necessary to cause the zoom level to change by a full integer value. More info: https://stackoverflow.com/a/44476181
> Add padding option to `defaultBounds`

- docs/api-reference/components/info-window.md
- src/components/__tests__/info-window.test.tsx
- src/components/info-window.tsx
Starting with the current beta-version, the Maps API will add new options to control content and visibility of the InfoWindow-header.
This adds a new headerContent prop that renders JSX content into the InfoWindows header.
fixes #378
> feat(infowindow): add new headerContent prop

- website/src/components/example/styled.js
Hello, this PR is an adjustment to the stylesheet for the example page so that more example tiles can be shown on the small screen, by shrinking extra margin/padding and adjusting the width of a tile.
Currently, even a relatively large-sized phone can only show only one thumbnail in a row.
The desktop view remains the same.
> docs(examples): show more example tiles on small screen

- README.md
Replace deprecated Marker with AdvancedMarker. Also adding a mapId for AdvancedMarker to work. Partially fixing #299
> Fix Marker deprecation in  README.md

- docs/api-reference/components/map.md
- src/components/__tests__/map.test.tsx
- src/components/info-window.tsx
- src/components/map/index.tsx
- src/components/map/use-map-instance.ts
- src/components/map/use-map-options.ts
This fixes #471 and a related issue with the new `colorScheme` option.
The cache-key used by the `reuseMaps` functionality only contained the mapId and not the other map options that can't be changed after the map has been created (`colorScheme` and `renderingType`). 
- add support for renderingType
- add support for colorScheme
- add missing options to mapOptionKeys
- update docs with new props
- update tests for props that can't be changed after map creation
Fixes #471
> fix(map): add support for new and missing mapOptions

- src/components/__tests__/map.test.tsx
- src/components/map/use-map-instance.ts
when color-scheme and/or rendering-type aren't specified, they were still passed as properties with undefined value to the google.maps.Map-constructor.
This is fixed here, along with the test that failed to detect that problem.
> fix(map): undefined rendering-type and color-scheme

- src/index.ts
Typescript versions prior to 5.5 automatically emitted triple-slash directives for types used in the exported definitions. This was changed in 5.5, which could lead to situations where the google.maps types aren't properly picked up in a project using this package.
Adding a type-reference ourselves should help in those cases.
See https://devblogs.microsoft.com/typescript/announcing-typescript-5-5/#simplified-reference-directive-declaration-emit
fixes #519
> fix(types): add types-reference to google.maps

- src/components/api-provider.tsx
Prevented unnecessary updating of context during AdvancedMarkers rendering
> [Bug 550] Optimized loadedLibraries reducer

- docs/api-reference/components/api-provider.md
- src/components/__tests__/api-provider.test.tsx
- src/components/api-provider.tsx
Resolves #533 
- Added onError to the list of API Provider props which will be called in case of an error when loading the Maps API. 
- Updated the mock in API Provider test to be able to simulate an error
- Added a unit test for the new functionality
- Added "Error Handling" section to the API Provider docs which mentions the new onError prop
I added the old console.error part to the else block so that there would be no error message in the console when running tests.
> feat: "onError" prop for api provider

- examples/advanced-marker-interaction/src/app.tsx
- examples/advanced-marker-interaction/src/control-panel.tsx
- examples/custom-marker-clustering/src/app.tsx
- examples/custom-marker-clustering/src/components/feature-marker.tsx
- examples/custom-marker-clustering/src/components/features-cluster-marker.tsx
- examples/custom-marker-clustering/src/style.css
- src/components/__tests__/advanced-marker.test.tsx
- src/components/advanced-marker.tsx
- src/components/info-window.tsx
- src/components/pin.tsx
First draft for improved and more robust advanced marker anchoring. Still needs some testing...
Main change is moving away from the "0, 0" div for the anchoring reset. That seemed to cause problems in a few situations
This should address and fix:
- #569 
- #559
- #542 
- #560
> fix: advanced marker anchoring

- src/components/__tests__/map-control.test.tsx
- src/components/__tests__/map.test.tsx
- src/components/__tests__/marker.test.tsx
- src/components/__tests__/pin.test.tsx
- src/components/advanced-marker.tsx
- src/components/api-provider.tsx
- src/components/info-window.tsx
- src/components/map-control.tsx
- src/components/map/auth-failure-message.tsx
- src/components/map/index.tsx
- src/components/marker.tsx
- src/components/pin.tsx
- src/hooks/__tests__/api-loading.test.tsx
- src/hooks/__tests__/use-map.test.tsx
Adding an explicit type to the components we export avoids typescript from inferring the type as JSX.Element, which is incompatible with some react-versions.
> fix: add explicit type for exported function components

- docs/guides/migrating-from-react-wrapper.md
- docs/table-of-contents.json
- examples/react-wrapper-migration/README.md
- examples/react-wrapper-migration/index.html
- examples/react-wrapper-migration/package.json
- examples/react-wrapper-migration/src/app.tsx
- examples/react-wrapper-migration/src/wrapper.tsx
- examples/react-wrapper-migration/vite.config.js
Add a small example and documentation on how to migrate code written with the @googlemaps/react-wrapper library to @vis.gl/react-google-maps.
> docs: add documentation on migrating from @googlemaps/react-wrapper

- src/components/info-window.tsx
The `infowindowOptions`  was a new object on every render thus resulting in the infowindow getting closed when the map was panned or zoomed
addresses #628
> fix: use deep compare effect to prevent infowindow close

- examples/directions/README.md
- examples/directions/src/app.tsx
Implemented draggable map markers into the Directions example. Added comments into code to specify what is necessary for draggable directions. Mentioned feature in README. 
This will close #672
> [FEATURE] Draggable Directions example

- .gitignore
- examples/map-3d/src/map-3d/map-3d.tsx
On Fri 21 Feb, Google Maps released a breaking change that required mode="hybrid" added to the  <gmp-map-3d/> component. This change fixed that.
> fix: 3d map not loading correctly due to new parameter mode=hybrid not included

- src/libraries/api-loading-status.ts
Added `as const` to ensure that `APILoadingStatus` is the intended union type instead of `string`
> fix: ensure proper type inference of APILoadingStatus

- src/components/advanced-marker.tsx
Because there is a type predicate already, so we can [keep things consistent](https://github.com/visgl/react-google-maps/blob/42602d6c20d29b176c8e97ee568a9665aac69309/src/components/advanced-marker.tsx#L224).
> refactor: no `Node` type casting

- examples/places-ui-kit/src/app.tsx
- examples/places-ui-kit/src/components/place-details-marker.tsx
- examples/places-ui-kit/src/control-panel.tsx
The `configureFromPlace` function i no longer available.
The `size` option is no longer available on the `gmp-place-details` element.
- Refactor size dropdown to only have FULL/COMPACT options. Using `gmp-place-details`  for FULL and `gmp-place-details-compact` for COMPACT
- Configure component with webcomponent rather than the `configureFromPlace` function.
- Using `gmp-place-all-content` element to display all default options for both scenarios.
> docs: fix place-ui-kit example

- examples/custom-marker-clustering/src/hooks/use-map-viewport.ts
This PR updates the `custom-marker-clustering` example to delay cluster rendering until the map becomes idle, rather than reacting to every `bounds_changed` event during zoom.
While investigating [issue #563](https://github.com/visgl/react-google-maps/issues/563), I found that the aggressive re-clustering during zoom gestures may contribute to a rare but severe bug where the zoom level resets unexpectedly (sometimes to zero). This is especially noticeable with a large number of markers. See [comment](https://github.com/visgl/react-google-maps/issues/563#issuecomment-3128047435).
By aligning the behavior with how Google’s official `[js-markerclusterer](https://github.com/googlemaps/js-markerclusterer)`(https://github.com/googlemaps/js-markerclusterer) handles clustering (listening to the …
> fix: Update calc clusters to happen after Idle event - reduces issue 563

- src/libraries/__tests__/create-static-maps-url.test.ts
- src/libraries/create-static-maps-url/assemble-path-params.ts
Removes the paths grouping by style for the Static Maps url. Does not make sense to do that to save a few bytes. This caused issues when multiple paths with the same same styles need to be drawn that are not connected.
addresses #808
> fix: remove path grouping by style for static maps url
